typography_spectrum: 0.36160552594810724
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5884601366706192
  lightness: 0.9426909738685936
  saturation: 0.9016825051512569
  rhythmicContrast: 0.5219396501779556
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.074605627451092
analytics:
  google: null
  facebook: null
  twitter: null
name: ExclamazingPoint
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ExclamazingPoint
purpose: []
